### ISSUE TITLE
Script Terminates at 'Rows' because it is an empty collection...

### ISSUE THREAD

**Issue by scottsmail** [AsBuiltReport/AsBuiltReport.VMware.vSphere#44]
Sirs,

I'm new to AsBuilt.  Installed module for vsphere.  I'm running esxi 6.5 and powershell version 5.1.  Each time I attempt to run one of the example reports it stops at the same point.  See error below.  What am I missing?

New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.
At line:1 char:1
+ New-AsBuiltReport -Target 'vcenterserver' -Username 'administ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by imompero** [comment]
Same issue here, first time trying to run AsBuiltReport

**Comment by tpcarman** [comment]
Hi @scottsmail & @imompero,
I just posted an update a few hours before you posted your issue. I will need some more information in order to assist you.
Could you please run `Get-Module -ListAvailable -Name AsBuiltReport*` and provide the output. If the `AsBuiltReport.VMware.vSphere` module is at v1.0.0 then you will need to run `Upate-Module -Name AsBuiltReport.VMware.vSphere` to update to v1.0.4. 
If you are still experiencing issues after updating, could you please provide me with more of the screen output so that I can identify where the report is terminating. 
Thanks.

**Comment by scottsmail** [comment]
Her'es my output.  I'm on version 1.04.  I've also included my modified screen output (removed server names, IP addresses, etc...)  Let me know if you need any other info

[AsBuilt.txt](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/files/3179929/AsBuilt.txt)

[AsBuilt Error.txt](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/files/3179971/AsBuilt.Error.txt)

**Comment by tpcarman** [comment]
I have identified the issue. 
There were some sections of code which have been messed up during my last update. 
I will take some time to thoroughly review and test the script and post another update in the next few days.
Apologies for this.

**Comment by scottsmail** [comment]
@tpcarman thanks for the update!.  Looking forward to using AsBuilt in my environment.

**Comment by tpcarman** [comment]
Resolved in #55
