### ISSUE TITLE
The variable '$pscriboDocument' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by pythongitram** [AsBuiltReport/AsBuiltReport.VMware.vSphere#93]
Getting an error when running this command 
[SP]> Invoke-AsBuiltReport.VMware.vSphere -Target xxxxxxxxxx -Credential xxxxxxxxxxxxxxx
The variable '$pscriboDocument' cannot be retrieved because it has not been set.
At line:51 char:9
+         $pscriboDocument.Properties['Sections']++;
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (pscriboDocument:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

Id                : 
Level             : 0
Number            :
Name              : <vcenter name> 
Type              : PScribo.Section
Style             : Heading1
Tabs              : 0
IsExcluded        : False
Sections          : {}
Orientation       : Portrait
IsSectionBreak    : False
IsSectionBreakEnd : False

**Comment by tpcarman** [comment]
@pythongitram please refer to the installation instructions within the [README](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/blob/master/README.md) and the [Examples](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/blob/master/README.md#computer-examples) provided to correctly execute the report. 

You require the `AsBuiltReport.Core` PowerShell module, as well as the `VMware.PowerCLI` module in order to generate a report.

**Comment by pythongitram** [comment]
I have both AsBuiltReport.Core and VMware.PowerCLI module installed. Cannot we directly run this command invoke-asbui.....

**Comment by tpcarman** [comment]
As Built Report is modular in its design architecture. The `AsBuiltReport.VMware.vSphere` module works in conjunction with the `AsBuiltReport.Core` module. As previously mentioned, the documented examples and `README` provide clear instructions of how to generate a report. You cannot generate a report by simply running `Invoke-AsBuiltReport.VMware.vSphere.ps1`.
